import { withInstall } from '/@/utils';
import transferModal from './src/TransferModal.vue';
import flowModal from './src/FlowModal.vue';
import flowContent from './src/FlowContent.vue';
import nodeModal from './src/quality/NodeModal.vue';
import rejectModal from './src/RejectModal.vue';
import remarkModal from './src/RemarkModal.vue';
import stopModal from './src/StopModal.vue';
import disagreeModal from './src/DisagreeModal.vue';
import dismissalModal from './src/quality/DismissalModal.vue';
import sapModal from './src/quality/SAPModal.vue';
import basicInfo from './src/BasicInfo.vue';
import bindFactoryModal from './src/BindFactoryModal.vue';
import dynamicTable from './src/simple/DynamicTable.vue';
import originTable from './src/matchTable/OriginTable.vue';
import matchTable from './src/matchTable/index.vue';
import targetTable from './src/matchTable/TargetTable.vue';

export const TransferModal = withInstall(transferModal);
export const FlowModal = withInstall(flowModal);
export const FlowContent = withInstall(flowContent);
export const NodeModal = withInstall(nodeModal);
export const RejectModal = withInstall(rejectModal);
export const RemarkModal = withInstall(remarkModal);
export const StopModal = withInstall(stopModal);
export const DisagreeModal = withInstall(disagreeModal);
export const DismissalModal = withInstall(dismissalModal);
export const SAPModal = withInstall(sapModal);
export const BasicInfo = withInstall(basicInfo);
export const BindFactoryModal = withInstall(bindFactoryModal);
export const DynamicTable = withInstall(dynamicTable);
export const OriginTable = withInstall(originTable);
export const MatchTable = withInstall(matchTable);
export const TargetTable = withInstall(targetTable);
