import type { BaseVxeTableTypes } from '/@/views/dataAnalysis/components/BaseVxeTable/types';
import type { TFormItemOption } from '/@/views/dataAnalysis/components/BaseSearchForm/types';

import { commonSyOrgCodeFormOptions } from '/@/views/dataAnalysis/config';
import dayjs from 'dayjs';
import {
  commonMediumTextOption,
  commonMiniValueOption,
  commonValueOption,
  commonMediumValueOption,
} from '/@/views/dataAnalysis/components/BaseVxeTable/config';
import { EFormItemType } from '/@/views/dataAnalysis/components/BaseSearchForm/types';
import { transThouIntEx } from '/@/views/dataAnalysis/utils';

export const getAllColumns = (): BaseVxeTableTypes.Columns => {
  const columns: BaseVxeTableTypes.Columns = [
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'factory',
      width: 70,
      title: '厂区',
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'skopf',
      width: 70,
      title: '模块',
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'month',
      title: '月份',
      width: 60,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'bukrs',
      title: '公司编码',
      width: 80,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'company',
      title: '公司名称',
      width: 190,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'bookkeepingType',
      title: '存货类型/记账分类',
      width: 130,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'matnr',
      title: '物料编号',
      width: 120,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'werks',
      title: '工厂',
      width: 60,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'flgor',
      title: '库存地点编号',
      width: 100,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'flgobe',
      title: '库存地点名称',
      width: 100,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'batch',
      title: '批次',
      width: 70,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'matAcvId',
      title: '物料记账分类',
      width: 100,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'bnssc',
      title: '业务范围',
      width: 80,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'weight',
      title: '重量',
      width: 60,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'gewei',
      title: '重量单位',
      width: 80,
    },
    {
      ...commonMediumTextOption,
      headerAlign: 'center',
      field: 'meins',
      title: '计量单位',
      width: 80,
    },
    {
      ...commonMiniValueOption,
      headerAlign: 'center',
      field: 'unitPrice',
      title: '单价',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonValueOption,
      headerAlign: 'center',
      field: 'monthEndQuantity',
      title: '月末数量',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'monthEndAmountActual',
      title: '月末实际金额',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonValueOption,
      headerAlign: 'center',
      field: 'withinThreeMonths',
      title: '3个月以内',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonValueOption,
      headerAlign: 'center',
      field: 'threeToFourMonths',
      title: '3-4个月',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonValueOption,
      headerAlign: 'center',
      field: 'fourToFiveMonths',
      title: '4-5个月',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonValueOption,
      headerAlign: 'center',
      field: 'fiveToSixMonths',
      title: '5-6个月',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonValueOption,
      headerAlign: 'center',
      field: 'sixToTwelveMonths',
      title: '6-12个月',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonValueOption,
      headerAlign: 'center',
      field: 'oneToTwoYears',
      title: '1-2年',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonValueOption,
      headerAlign: 'center',
      field: 'moreThanTwoYears',
      title: '2-3年',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonValueOption,
      headerAlign: 'center',
      field: 'moreThanThreeYears',
      title: '3年以上',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'inventoryDepreciation',
      title: '存货跌价准备余额',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'ageProvision',
      title: '库龄计提',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'realProvision',
      title: '可变现净值计提',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'selPrice',
      title: '销售单价',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'lastYearSingleProvision',
      title: '以前年度单项计提',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'singleProvision',
      title: '单项计提',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'reason',
      title: '单项计提原因',
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'lastYearMention',
      title: '其中：以前年度计提跌价',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'provisionForThisYear',
      title: '其中：本年度计提跌价金额',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'isEdit',
      title: '编辑标识',
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      align: 'left',
      field: 'isApi',
      title: '数据抽取标识',
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'zDays',
      title: '库龄',
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'zDaysType',
      title: '库龄类型',
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'wjtQty',
      title: '未计提数量',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
    {
      ...commonMediumValueOption,
      headerAlign: 'center',
      field: 'wjtValue',
      title: '未计提金额',
      formatter: ({ cellValue }) => transThouIntEx(cellValue, '', 0, true),
      exportMethod: ({ row, column }) => transThouIntEx(row[column.field], '', 4),
    },
  ];

  return columns;
};

export const formOptions: TFormItemOption[] = [
  commonSyOrgCodeFormOptions,

  {
    type: EFormItemType.DATE_PICKER,
    default: dayjs().tz().subtract(1, 'month'),
    key: 'month',
    attrs: {
      picker: 'month',
    },
    getParam: value => {
      return { month: value.format('YYYY-MM') };
    },
  },
  {
    type: EFormItemType.SELECT,
    label: '法人',
    default: [],
    key: 'bukrs',
    attrs: {
      allowClear: false,
      mode: 'multiple',
    },
    options: [],
    getParam: value => {
      return { bukrs: value.join(';') };
    },
  },
];
