npmRegistryServer: "https://registry.npmmirror.com"

# 针对特定包使用不同的源
npmScopes:
  bin-wrapper:
    npmRegistryServer: "https://registry.npmjs.org"

# 网络超时配置（单位：毫秒）
httpTimeout: 600000

# 网络并发数
networkConcurrency: 8

# 启用严格 SSL（默认值，可以不写）
enableStrictSsl: true

