# 项目的唯一标识，必填
sonar.projectKey=lydc_web
# 项目名称
sonar.projectName=lydc_web
# 项目版本
sonar.projectVersion=1.0
#扫描目录
sonar.sources=src
#检测语言
sonar.language=js,ts
sonar.eslint.eslintconfigpath=.eslintrc
sonar.eslint.ruleconfigs=.eslintrc
#文件编码
sonar.sourceEncoding=UTF-8
# 排除特定文件夹（不进行分析）
sonar.exclusions=src/assets/**,src/views/system/printTemplate/components/**,src/sdk/**,src/plugins/vxe/**
#跳过证书验证
sonar.scanner.skipCertificateCheck=true
