import XEUtils from 'xe-utils';
import { useI18n } from '/@/hooks/web/useI18n';
const { t: $t } = useI18n();
// 格式化数量
const formatterQuantity = ({ cellValue }) => {
  if (!cellValue) return cellValue;
  return XEUtils.commafy(cellValue, { digits: 0 });
};
// 格式化金额
const formatterPrice = ({ cellValue }) => {
  if (!cellValue) return cellValue;
  return XEUtils.commafy(cellValue, { digits: 2 });
};

// 核心字段
export const keyFields = ['customerCode', 'factory', 'innerMaterialNumber', 'middleMaterialNumber', 'quantity1'];

export const columns = [
  {
    title: $t('dict.FcDataColumn.customerCode'),
    field: 'customerCode',
    width: 100,
    slots: {
      header: 'customerCode',
    },
  },
  {
    title: $t('dict.FcDataColumn.factory'),
    field: 'factory',
    width: 100,
  },
  {
    title: $t('dict.FcDataColumn.project'),
    field: 'project',
    width: 100,
  },
  {
    title: $t('dict.FcDataColumn.projectPhase'),
    field: 'projectPhase',
    width: 100,
  },
  {
    title: $t('dict.FcDataColumn.innerMaterialNumber'),
    field: 'innerMaterialNumber',
    minWidth: 130,
  },
  {
    title: $t('dict.FcDataColumn.middleMaterialNumber'),
    field: 'middleMaterialNumber',
    minWidth: 130,
  },
  {
    title: $t('dict.FcDataColumn.factoryAreaName'),
    field: 'factoryAreaName',
    width: 120,
  },
  {
    title: $t('dict.FcDataColumn.useQuantity'),
    field: 'useQuantity',
    width: 100,
  },
  {
    title: $t('dict.FcDataColumn.vmiOrJit'),
    field: 'vmiOrJit',
    width: 100,
  },
  {
    title: $t('dict.FcDataColumn.tradeCurrency'),
    field: 'tradeCurrency',
    width: 100,
  },
  {
    title: $t('dict.FcDataColumn.lastWeekDemandQuantity'),
    field: 'lastWeekDemandQuantity',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: $t('dict.FcDataColumn.lastWeekOweQuantity'),
    field: 'lastWeekOweQuantity',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: $t('dict.FcDataColumn.changeRatio'),
    field: 'changeRatio',
    width: 130,
  },
  {
    title: $t('dict.FcDataColumn.customerInventory'),
    field: 'customerInventory',
    width: 110,
    formatter: formatterQuantity,
  },
  {
    title: $t('dict.FcDataColumn.customerInventoryUseWeek'),
    field: 'customerInventoryUseWeek',
    width: 130,
  },
  {
    title: $t('dict.FcDataColumn.remark1'),
    field: 'remark1',
    width: 130,
  },
  {
    title: $t('dict.FcDataColumn.finishedProductInventory'),
    field: 'finishedProductInventory',
    width: 100,
  },
  {
    title: 'WK1',
    field: 'quantity1',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK2',
    field: 'quantity2',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK3',
    field: 'quantity3',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK4',
    field: 'quantity4',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK5',
    field: 'quantity5',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK6',
    field: 'quantity6',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK7',
    field: 'quantity7',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK8',
    field: 'quantity8',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK9',
    field: 'quantity9',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK10',
    field: 'quantity10',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK11',
    field: 'quantity11',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK12',
    field: 'quantity12',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK13',
    field: 'quantity13',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK14',
    field: 'quantity14',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK15',
    field: 'quantity15',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK16',
    field: 'quantity16',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK17',
    field: 'quantity17',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK18',
    field: 'quantity18',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK19',
    field: 'quantity19',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK20',
    field: 'quantity20',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK21',
    field: 'quantity21',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK22',
    field: 'quantity22',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK23',
    field: 'quantity23',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK24',
    field: 'quantity24',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK25',
    field: 'quantity25',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK26',
    field: 'quantity26',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK27',
    field: 'quantity27',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK28',
    field: 'quantity28',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK29',
    field: 'quantity29',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK30',
    field: 'quantity30',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK31',
    field: 'quantity31',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK32',
    field: 'quantity32',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK33',
    field: 'quantity33',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK34',
    field: 'quantity34',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: 'WK35',
    field: 'quantity35',
    width: 100,
    formatter: formatterQuantity,
  },
  {
    title: $t('dict.FcDataColumn.materialIsMore'),
    field: 'materialIsMore',
    width: 185,
  },
  {
    title: $t('dict.FcDataColumn.remark2'),
    field: 'remark2',
  },
  {
    title: $t('dict.FcDataColumn.price'),
    field: 'price',
    auth: 'price',
    width: 100,
  },
  {
    title: $t('dict.FcDataColumn.currency'),
    field: 'currency',
    width: 100,
  },
  {
    title: 'WK1',
    field: 'totalPrice1',
    auth: 'totalPrice1',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK2',
    field: 'totalPrice2',
    auth: 'totalPrice2',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK3',
    field: 'totalPrice3',
    auth: 'totalPrice3',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK4',
    field: 'totalPrice4',
    auth: 'totalPrice4',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK5',
    field: 'totalPrice5',
    auth: 'totalPrice5',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK6',
    field: 'totalPrice6',
    auth: 'totalPrice6',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK7',
    field: 'totalPrice7',
    auth: 'totalPrice7',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK8',
    field: 'totalPrice8',
    auth: 'totalPrice8',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK9',
    field: 'totalPrice9',
    auth: 'totalPrice9',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK10',
    field: 'totalPrice10',
    auth: 'totalPrice10',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK11',
    field: 'totalPrice11',
    auth: 'totalPrice11',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK12',
    field: 'totalPrice12',
    auth: 'totalPrice12',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK13',
    field: 'totalPrice13',
    auth: 'totalPrice13',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK14',
    field: 'totalPrice14',
    auth: 'totalPrice14',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK15',
    field: 'totalPrice15',
    auth: 'totalPrice15',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK16',
    field: 'totalPrice16',
    auth: 'totalPrice16',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK17',
    field: 'totalPrice17',
    auth: 'totalPrice17',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK18',
    field: 'totalPrice18',
    auth: 'totalPrice18',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK19',
    field: 'totalPrice19',
    auth: 'totalPrice19',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK20',
    field: 'totalPrice20',
    auth: 'totalPrice20',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK21',
    field: 'totalPrice21',
    auth: 'totalPrice21',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK22',
    field: 'totalPrice22',
    auth: 'totalPrice22',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK23',
    field: 'totalPrice23',
    auth: 'totalPrice23',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK24',
    field: 'totalPrice24',
    auth: 'totalPrice24',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK25',
    field: 'totalPrice25',
    auth: 'totalPrice25',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK26',
    field: 'totalPrice26',
    auth: 'totalPrice26',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK27',
    field: 'totalPrice27',
    auth: 'totalPrice27',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK28',
    field: 'totalPrice28',
    auth: 'totalPrice28',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK29',
    field: 'totalPrice29',
    auth: 'totalPrice29',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK30',
    field: 'totalPrice30',
    auth: 'totalPrice30',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK31',
    field: 'totalPrice31',
    auth: 'totalPrice31',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK32',
    field: 'totalPrice32',
    auth: 'totalPrice32',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK33',
    field: 'totalPrice33',
    auth: 'totalPrice33',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK34',
    field: 'totalPrice34',
    auth: 'totalPrice34',
    width: 100,
    formatter: formatterPrice,
  },
  {
    title: 'WK35',
    field: 'totalPrice35',
    auth: 'totalPrice35',
    width: 100,
    formatter: formatterPrice,
  },
];
