import { getlistbycheckprojectname } from '/@/api/productionDeal/ipqc';
import { useI18n } from '/@/hooks/web/useI18n';
import { useBaseStore } from '/@/store/modules/base';
const { t } = useI18n();
const baseStore = useBaseStore();
const { data: externalsCheckCode } = await getlistbycheckprojectname('模具外观');
const { data: packageSpecificationCheckCode } = await getlistbycheckprojectname('模具包规');

export const EXTERNALS_MODULE_TEMPLATE = {
  checkCode: null,
  checkResult: 'OK',
  ngQuantity: null,
  remark: null,
  attachmentId: null,
};
export const DIMENSIONS_MODULE_TEMPLATE = {
  drawingSize: null,
  tolerance: '0.03',
  measureTools: null,
  actualSize1: null,
  actualSize2: null,
  actualSize3: null,
  remark: null,
};

export const ANGLE_MODULE_TEMPLATE = {
  bladeType: null,
  bladeAngleA1: null,
  bladeAngleA2: null,
  bladeEdgeAngleA3: null,
  bladeEdgeAngleA4: null,
  bladeCheckResult: null,
  bladeNgQuantity: null,
  angleRemark: null,
};

export const HEIGHT_MODULE_TEMPLATE = {
  knifeHeightType: null,
  bladeHeightH1: null,
  bladeHeightH2: null,
  bladeEdgeHeightH3: null,
  bladeEdgeHeightH4: null,
  knifeHeightCheckResult: null,
  knifeHeightNgQuantity: null,
  heightRemark: null,
};

export const externals_columns: any[] = [
  {
    name: '检测项',
    slots: { title: 'checkCodeTitle' },
    titleHelpMessage: '必填',
    dataIndex: 'checkCode',
    isEdit: true,
    isRequired: true,
    inputType: '',
    cpmType: 'ApiSelect',
    cpmSetting: {
      allowClear: false,
      showArrow: false,
      open: false,
      options: externalsCheckCode,
      fieldNames: {
        value: 'Code',
        label: 'CheckClass',
      },
      // api: () => getlistbycheckprojectname('模具外观'),
      // placeholder: '请输入',
      // showSearch: false,
      // resultField: 'data',
      // valueField: 'Code',
      // labelField: 'CheckClass',
      // filterOption: false,
      immediate: false,
    },
  },
  {
    name: t('dict.CommonCol.detectionResult'),
    dataIndex: 'checkResult',
    slots: { title: 'checkResultTitle' },
    isEdit: true,
    isRequired: true,
    inputType: '',
    cpmType: 'ApiSelect',
    cpmSetting: {
      placeholder: '请选择',
      showSearch: false,
      resultField: 'data',
      valueField: 'enCode',
      labelField: 'fullName',
      filterOption: false,
      immediate: true,
      api: () => baseStore.getDictionaryData('ProcessRules.DecideResult'),
    },
  },
  {
    title: t('dict.CommonCol.ngNum'),
    dataIndex: 'ngQuantity',
    // slots: { title: 'ngQuantityTitle' },
    isEdit: true,
    isRequired: false,
    inputType: 'number',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  { title: t('dict.CommonCol.remark'), dataIndex: 'remark', isEdit: true, inputType: '', cpmType: 'Input', cpmSetting: { placeholder: '请输入' } },
  {
    title: t('dict.CommonCol.file'),
    dataIndex: 'attachmentId',
    isEdit: false,
    inputType: '',
    cpmType: 'upload',
    cpmSetting: { placeholder: '请输入' },
  },
];

export const dimensions_columns: any[] = [
  {
    name: '图面尺寸(mm)',
    dataIndex: 'drawingSize',
    slots: { title: 'drawingSizeTitle' },
    isRequired: true,
    isEdit: true,
    inputType: 'float',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  { title: '公差(+/-)', dataIndex: 'tolerance', isEdit: true, inputType: 'float', cpmType: 'Input', cpmSetting: { placeholder: '请输入', min: 0 } },
  {
    title: '测量工具',
    dataIndex: 'measureTools',
    isEdit: true,
    inputType: '',
    cpmType: 'ApiSelect',
    cpmSetting: {
      placeholder: '请输入',
      showSearch: false,
      resultField: 'data',
      valueField: 'enCode',
      labelField: 'fullName',
      filterOption: false,
      immediate: true,
      api: () => baseStore.getDictionaryData('MeasureTools'),
    },
  },
  { title: '实测尺寸(mm)', dataIndex: 'actualSize1', isEdit: true, inputType: 'float', cpmType: 'Input', cpmSetting: { placeholder: '请输入', min: 0 } },
  { title: '', dataIndex: 'actualSize2', isEdit: true, inputType: 'float', cpmType: 'Input', cpmSetting: { placeholder: '请输入' } },
  { title: '', dataIndex: 'actualSize3', isEdit: true, inputType: 'float', cpmType: 'Input', cpmSetting: { placeholder: '请输入' } },
  {
    name: t('dict.CommonCol.detectionResult'),
    dataIndex: 'checkResult',
    slots: { title: 'checkResultTitle' },
    isEdit: true,
    isRequired: true,
    inputType: '',
    cpmType: 'ApiSelect',
    cpmSetting: {
      placeholder: '请选择',
      showSearch: false,
      resultField: 'data',
      valueField: 'enCode',
      labelField: 'fullName',
      filterOption: false,
      immediate: true,
      api: () => baseStore.getDictionaryData('ProcessRules.DecideResult'),
    },
  },
  {
    name: 'NG数',
    dataIndex: 'ngQuantity',
    slots: { title: 'ngQuantityTitle' },
    isEdit: true,
    isRequired: false,
    inputType: 'number',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  { title: t('dict.CommonCol.remark'), dataIndex: 'remark', isEdit: true, inputType: '', cpmType: 'Input', cpmSetting: { placeholder: '请输入' } },
];

export const packageSpecification_columns: any[] = [
  {
    name: '检测项',
    dataIndex: 'checkCode',
    slots: { title: 'checkCodeTitle' },
    isEdit: true,
    isRequired: true,
    inputType: '',
    cpmType: 'ApiSelect',
    cpmSetting: {
      allowClear: false,
      showArrow: false,
      open: false,
      options: packageSpecificationCheckCode,
      fieldNames: {
        value: 'Code',
        label: 'CheckClass',
      },
      immediate: false,
    },
  },
  {
    name: t('dict.CommonCol.detectionResult'),
    dataIndex: 'checkResult',
    slots: { title: 'checkResultTitle' },
    isEdit: true,
    isRequired: true,
    inputType: '',
    cpmType: 'ApiSelect',
    cpmSetting: {
      placeholder: '请选择',
      showSearch: false,
      resultField: 'data',
      valueField: 'enCode',
      labelField: 'fullName',
      filterOption: false,
      immediate: true,
      api: () => baseStore.getDictionaryData('ProcessRules.DecideResult'),
    },
  },
  {
    title: t('dict.CommonCol.ngNum'),
    dataIndex: 'ngQuantity',
    // slots: { title: 'ngQuantityTitle' },
    isEdit: true,
    isRequired: false,
    inputType: 'number',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  { title: t('dict.CommonCol.remark'), dataIndex: 'remark', isEdit: true, inputType: '', cpmType: 'Input', cpmSetting: { placeholder: '请输入' } },
  { title: t('dict.CommonCol.file'), dataIndex: 'attachmentId', isEdit: false, inputType: '', cpmType: 'upload', cpmSetting: { placeholder: '请输入' } },
];

export const angle_columns: any[] = [
  {
    name: '刀锋类型',
    dataIndex: 'bladeType',
    slots: { title: 'bladeTypeTitle' },
    isEdit: true,
    isRequired: true,
    inputType: '',
    cpmType: 'ApiSelect',
    cpmSetting: {
      placeholder: '请选择',
      showSearch: false,
      resultField: 'data',
      valueField: 'enCode',
      labelField: 'fullName',
      filterOption: false,
      immediate: true,
      api: () => baseStore.getDictionaryData('bladeType'),
    },
  },
  {
    title: `(${t('dict.CommonCol.bladeAngle', ['A1'])})`,
    dataIndex: 'bladeAngleA1',
    isEdit: true,
    inputType: 'float',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  {
    title: `(${t('dict.CommonCol.bladeAngle', ['A2'])})`,
    dataIndex: 'bladeAngleA2',
    isEdit: true,
    inputType: 'float',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  {
    title: `(${t('dict.CommonCol.bladeEdgeAngle', ['A3'])})`,
    dataIndex: 'bladeEdgeAngleA3',
    isEdit: true,
    inputType: 'float',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  {
    title: `(${t('dict.CommonCol.bladeEdgeAngle', ['A4'])})`,
    dataIndex: 'bladeEdgeAngleA4',
    isEdit: true,
    inputType: 'float',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  {
    name: t('dict.CommonCol.detectionResult'),
    dataIndex: 'bladeCheckResult',
    slots: { title: 'bladeCheckResultTitle' },
    isEdit: true,
    isRequired: true,
    inputType: '',
    cpmType: 'ApiSelect',
    cpmSetting: {
      placeholder: '请选择',
      showSearch: false,
      resultField: 'data',
      valueField: 'enCode',
      labelField: 'fullName',
      filterOption: false,
      immediate: true,
      api: () => baseStore.getDictionaryData('ProcessRules.DecideResult'),
    },
  },
  {
    name: t('dict.CommonCol.ngNum'),
    dataIndex: 'bladeNgQuantity',
    slots: { title: 'bladeNgQuantityTitle' },
    isEdit: true,
    isRequired: false,
    inputType: 'number',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  { title: t('dict.CommonCol.remark'), dataIndex: 'angleRemark', isEdit: true, inputType: '', cpmType: 'Input', cpmSetting: { placeholder: '请输入' } },
];

export const height_columns: any[] = [
  {
    name: '刀高类型',
    dataIndex: 'knifeHeightType',
    slots: { title: 'knifeHeightTypeTitle' },
    isEdit: true,
    isRequired: true,
    inputType: '',
    cpmType: 'ApiSelect',
    cpmSetting: {
      placeholder: '请选择',
      showSearch: false,
      resultField: 'data',
      valueField: 'enCode',
      labelField: 'fullName',
      filterOption: false,
      immediate: true,
      api: () => baseStore.getDictionaryData('knifeHeightType'),
    },
  },
  {
    title: `(${t('dict.CommonCol.bladeEdgeAngle', ['H1'])})`,
    dataIndex: 'bladeHeightH1',
    isEdit: true,
    inputType: 'float',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  {
    title: `(${t('dict.CommonCol.bladeEdgeAngle', ['H2'])})`,
    dataIndex: 'bladeHeightH2',
    isEdit: true,
    inputType: 'float',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  {
    title: `(${t('dict.CommonCol.bladeEdgeHeight', ['H3'])})`,
    dataIndex: 'bladeEdgeHeightH3',
    isEdit: true,
    inputType: 'float',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  {
    title: `(${t('dict.CommonCol.bladeEdgeHeight', ['H4'])})`,
    dataIndex: 'bladeEdgeHeightH4',
    isEdit: true,
    inputType: 'float',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  {
    name: t('dict.CommonCol.detectionResult'),
    dataIndex: 'knifeHeightCheckResult',
    slots: { title: 'knifeHeightCheckResultTitle' },
    isEdit: true,
    isRequired: true,
    inputType: '',
    cpmType: 'ApiSelect',
    cpmSetting: {
      placeholder: '请选择',
      showSearch: false,
      resultField: 'data',
      valueField: 'enCode',
      labelField: 'fullName',
      filterOption: false,
      immediate: true,
      api: () => baseStore.getDictionaryData('ProcessRules.DecideResult'),
    },
  },
  {
    title: t('dict.CommonCol.ngNum'),
    dataIndex: 'knifeHeightNgQuantity',
    isEdit: true,
    isRequired: false,
    inputType: 'number',
    cpmType: 'Input',
    cpmSetting: { placeholder: '请输入', min: 0 },
  },
  { title: t('dict.CommonCol.remark'), dataIndex: 'heightRemark', isEdit: true, inputType: '', cpmType: 'Input', cpmSetting: { placeholder: '请输入' } },
];
