import {
  commonTextOption,
  commonMediumTextOption,
  commonValueOption,
  commonMediumFormatValueOption,
  commonDateOption,
  getFormatter,
} from '/@/views/dataAnalysis/components/BaseVxeTable/config';
import { dimensionCommonFormOptions } from '../../config';
import { BaseVxeTableTypes, EColumnType } from '/@/views/dataAnalysis/components/BaseVxeTable/types';
import { TFormItemOption } from '/@/views/dataAnalysis/components/BaseSearchForm/types';
// 表单配置
export const formOptions: TFormItemOption[] = [...dimensionCommonFormOptions];

export const getAllColumns = (): BaseVxeTableTypes.Columns => {
  const columns: BaseVxeTableTypes.Columns = [
    { type: 'seq', title: '序号', width: 50, fixed: 'left' },
    //  "factory" => "厂区",
    // "year" => "年",
    // "month" => "月",
    // "week" => "周",
    // "dayDateStr" => "过账日期",
    // "gsber" => "仓库业务范围",
    { ...commonTextOption, title: '厂区', field: 'factory' },
    { ...commonTextOption, title: '年', field: 'year' },
    { ...commonTextOption, title: '月', field: 'month' },
    { ...commonTextOption, title: '周', field: 'week' },
    { ...commonTextOption, title: '过账日期', field: 'dayDateStr' },
    { ...commonTextOption, title: '仓库业务范围', field: 'gsber' },
    // "werks" => "工厂",
    // "batch" => "批次",
    // "zqtyP" => "过账数量",
    // "zczdj" => "产值单价",
    // "zcpcz" => "成品产值",
    // "matnr" => "物料编码",
    // "zdoctyp" => "单据类型",
    // "zwerksMb" => "目标工厂",
    // "lgort" => "库存地点",
    { ...commonTextOption, title: '工厂', field: 'werks' },
    { ...commonTextOption, title: '批次', field: 'batch' },
    { ...commonMediumFormatValueOption, width: 80, title: '过账数量', field: 'zqtyP' },
    { ...commonMediumFormatValueOption, width: 80, title: '产值单价', field: 'zczdj', formatter: getFormatter({ decimal: 6 }) },
    { ...commonMediumFormatValueOption, width: 80, title: '成品产值', field: 'zcpcz' },
    { ...commonTextOption, title: '物料编码', field: 'matnr' },
    { ...commonTextOption, title: '单据类型', field: 'zdoctyp' },
    { ...commonTextOption, title: '目标工厂', field: 'zwerksMb' },
    { ...commonTextOption, title: '库存地点', field: 'lgort' },
    // "zlgortMb" => "目标库存地点",
    // "zno" => "单号",
    // "zitem" => "行号",
    // "znoSpli" => "拆分行",
    // "zdoctypTxt" => "单据类型描述",
    // "bukrs" => "公司代码",
    // "zlltyp" => "领料类型",
    // "zrequser" => "申请人",
    // "zreqdep" => "申请部门",
    { ...commonTextOption, title: '目标库存地点', field: 'zlgortMb' },
    { ...commonTextOption, title: '单号', field: 'zno' },
    { ...commonMediumFormatValueOption, width: 60, title: '行号', field: 'zitem' },
    { ...commonMediumFormatValueOption, width: 80, title: '拆分行', field: 'znoSpli' },
    { ...commonTextOption, title: '单据类型描述', field: 'zdoctypTxt' },
    { ...commonTextOption, title: '公司代码', field: 'bukrs' },
    { ...commonTextOption, title: '领料类型', field: 'zlltyp' },
    { ...commonTextOption, title: '申请人', field: 'zrequser' },
    { ...commonTextOption, title: '申请部门', field: 'zreqdep' },
    // "zidateStr" => "创建日期",
    // "zpuserName" => "过账者",
    // "zpdateStr" => "过账日期",
    // "mblnr" => "物料凭证",
    // "aufnr" => "内部订单号",
    // "maktx" => "物料描述",
    { ...commonTextOption, title: '创建日期', field: 'zidateStr' },
    { ...commonTextOption, title: '过账者', field: 'zpuserName' },
    { ...commonTextOption, title: '过账日期', field: 'zpdateStr' },
    { ...commonTextOption, title: '物料凭证', field: 'mblnr' },
    { ...commonTextOption, title: '内部订单号', field: 'aufnr' },
    { ...commonTextOption, title: '物料描述', field: 'maktx' },
    // "zqty" => "数量",
    { ...commonMediumFormatValueOption, width: 60, title: '数量', field: 'zqty' },
    { ...commonTextOption, title: '单位', field: 'meins' },
    // "dmbtr" => "本位币金额",
    { ...commonMediumFormatValueOption, width: 80, title: '本位币金额', field: 'dmbtr' },
    // "zsjcb" => "实际成本",
    { ...commonMediumFormatValueOption, width: 80, title: '实际成本', field: 'zsjcb' },
    // "waers" => "币别",
    // "lgobe" => "库存地点描述",
    // "charg" => "批次",
    // "zlgobeMb" => "目标库存地点描述",
    // "kostl" => "成本中心",
    { ...commonTextOption, title: '币别', field: 'waers' },
    { ...commonTextOption, title: '库存地点描述', field: 'lgobe' },
    { ...commonTextOption, title: '批次', field: 'charg' },
    { ...commonTextOption, title: '目标库存地点描述', field: 'zlgobeMb' },
    { ...commonTextOption, title: '成本中心', field: 'kostl' },
    // "kostlTxt" => "成本中心描述",
    { ...commonTextOption, title: '成本中心描述', field: 'kostlTxt' },
    // "abtei" => "成本中心业务范围",
    // "zlgortP" => "过账库存地点",
    // "zlgobeP" => "过账库存地点描述",
    // "zpartner" => "客户",
    // "znameP" => "客户名称",
    // "zmark" => "行项目备注",
    { ...commonTextOption, title: '成本中心业务范围', field: 'abtei' },
    { ...commonTextOption, title: '过账库存地点', field: 'zlgortP' },
    { ...commonTextOption, title: '过账库存地点描述', field: 'zlgobeP' },
    { ...commonTextOption, title: '客户', field: 'zpartner' },
    { ...commonTextOption, title: '客户名称', field: 'znameP' },
    { ...commonTextOption, title: '行项目备注', field: 'zmark' },
  ];
  return columns;
};
