// 表格数据列配置
export const TABLE_COLUMNS = [
  {
    title: 'excel行号',
    dataIndex: 'Number',
    width: 120,
    key: 'Number',
    // scopedSlots: { customRender: 'Id' },
  },
  {
    title: '数据',
    dataIndex: 'ErrorMsg',
    key: 'ErrorMsg',
    sorter: (a, b) => a.ErrorMsg.localeCompare(b.ErrorMsg),
  },
  {
    title: '内部项目代码',
    dataIndex: 'InsideProjectCode',
    key: 'InsideProjectCode',
    sorter: (a, b) => a.InsideProjectCode.localeCompare(b.InsideProjectCode),
  },
  {
    title: '直接客户料号',
    dataIndex: 'ImmediateCustomerPartNumber',
    key: 'ImmediateCustomerPartNumber',
    sorter: (a, b) => a.InsideProjectCode.localeCompare(b.InsideProjectCode),
  },
  {
    title: '直接客户信息',
    dataIndex: 'ImmediateCustomerCode',
    key: 'ImmediateCustomerCode',
    sorter: (a, b) => a.ImmediateCustomerCode.localeCompare(b.ImmediateCustomerCode),
  },
  {
    title: '直接客户项目代码',
    dataIndex: 'ImmediateCustomerProjectCode',
    key: 'ImmediateCustomerProjectCode',
    width: 170,
    sorter: (a, b) => a.ImmediateCustomerProjectCode.localeCompare(b.ImmediateCustomerProjectCode),
  },
  {
    title: '终端客户代码',
    dataIndex: 'TerminalCustomerCode',
    key: 'TerminalCustomerCode',
    sorter: (a, b) => a.TerminalCustomerCode.localeCompare(b.TerminalCustomerCode),
  },
  {
    title: '终端客户料号',
    dataIndex: 'TerminalCustomerPartNumber',
    key: 'TerminalCustomerPartNumber',
    sorter: (a, b) => a.TerminalCustomerPartNumber.localeCompare(b.TerminalCustomerPartNumber),
  },
  {
    title: '出货形态',
    dataIndex: 'ShipPattern',
    key: 'ShipPattern',
    sorter: (a, b) => a.ShipPattern.localeCompare(b.ShipPattern),
  },
  // {
  //   title: '直接客户图号',
  //   dataIndex: 'ImmediateCustomerDrawingNumber',
  //   key: 'ImmediateCustomerDrawingNumber',
  //   sorter: (a, b) => a.ImmediateCustomerDrawingNumber.localeCompare(b.ImmediateCustomerDrawingNumber),
  // },
  {
    title: 'Config',
    dataIndex: 'Config',
    key: 'Config',
    sorter: (a, b) => a.Config.localeCompare(b.Config),
  },
  {
    title: '工厂',
    dataIndex: 'Factory',
    key: 'Factory',
    sorter: (a, b) => a.Factory.localeCompare(b.Factory),
  },
  {
    title: '主要制程',
    dataIndex: 'MainProcess',
    key: 'MainProcess',
    sorter: (a, b) => a.MainProcess.localeCompare(b.MainProcess),
  },
  {
    title: '申请人',
    dataIndex: 'ApplyUserName',
    key: 'ApplyUserName',
    sorter: (a, b) => a.ApplyUserName.localeCompare(b.ApplyUserName),
  },
  {
    title: '申请部门',
    dataIndex: 'ApplyDeptName',
    key: 'ApplyDeptName',
    sorter: (a, b) => a.ApplyDeptName.localeCompare(b.ApplyDeptName),
  },
  {
    title: '申请日期',
    dataIndex: 'ApplyDate',
    key: 'ApplyDate',
    sorter: (a, b) => a.ApplyDate.localeCompare(b.ApplyDate),
  },
  {
    title: '失效日期',
    dataIndex: 'ExpiryDate',
    key: 'ExpiryDate',
    sorter: (a, b) => a.ExpiryDate.localeCompare(b.ExpiryDate),
  },
  // {
  //   title: '截止日期',
  //   dataIndex: 'ExpiryDate',
  //   key: 'ExpiryDate',
  //   sorter: (a, b) => a.ExpiryDate.localeCompare(b.ExpiryDate),
  // },
  // {
  //   title: '保税类型',
  //   dataIndex: 'OrgId',
  //   key: 'OrgId',
  //   sorter: (a, b) => a.InsideProjectCode.localeCompare(b.InsideProjectCode),
  // },
  {
    title: '申请原因',
    dataIndex: 'ApplyReason',
    key: 'ApplyReason',
    sorter: (a, b) => a.ApplyReason.localeCompare(b.ApplyReason),
  },
  {
    title: '终端项目代码',
    dataIndex: 'TerminalCustomerProjectCode',
    key: 'TerminalCustomerProjectCode',
    sorter: (a, b) => a.TerminalCustomerProjectCode.localeCompare(b.TerminalCustomerProjectCode),
  },
  // {
  //   title: '终端客户版本号',
  //   dataIndex: 'TerminalCustomerVersion',
  //   key: 'TerminalCustomerVersion',
  //   sorter: (a, b) => a.TerminalCustomerVersion.localeCompare(b.TerminalCustomerVersion),
  // },
  {
    title: '产品描述',
    dataIndex: 'ProductDesc',
    key: 'ProductDesc',
    sorter: (a, b) => a.ProductDesc.localeCompare(b.ProductDesc),
  },
  // {
  //   title: '客户图号',
  //   dataIndex: 'ImmediateCustomerDrawingNumber',
  //   key: 'ImmediateCustomerDrawingNumber',
  //   sorter: (a, b) => a.ImmediateCustomerDrawingNumber.localeCompare(b.ImmediateCustomerDrawingNumber),
  // },
  {
    title: '终端项目代码',
    dataIndex: 'TerminalCustomerProjectCode',
    key: 'TerminalCustomerProjectCode',
    sorter: (a, b) => a.TerminalCustomerProjectCode.localeCompare(b.TerminalCustomerProjectCode),
  },
  {
    title: '直接客户料号版本',
    dataIndex: 'ImmediateCustomerPartVersion',
    key: 'ImmediateCustomerPartVersion',
    width: 180,
    sorter: (a, b) => a.ImmediateCustomerPartVersion.localeCompare(b.ImmediateCustomerPartVersion),
  },
  {
    title: '旧版客户料号',
    dataIndex: 'InsidePartNumberOld',
    key: 'InsidePartNumberOld',
    sorter: (a, b) => a.InsidePartNumberOld.localeCompare(b.InsidePartNumberOld),
  },
  // {
  //   title: '客户图纸',
  //   dataIndex: 'OrgId',
  //   key: 'OrgId',
  //   sorter: (a, b) => a.InsideProjectCode.localeCompare(b.InsideProjectCode),
  // },
  // {
  //   title: '脱敏图纸',
  //   dataIndex: 'OrgId',
  //   key: 'OrgId',
  //   sorter: (a, b) => a.InsideProjectCode.localeCompare(b.InsideProjectCode),
  // },
  // {
  //   title: '工程图纸',
  //   dataIndex: 'OrgId',
  //   key: 'OrgId',
  //   sorter: (a, b) => a.InsideProjectCode.localeCompare(b.InsideProjectCode),
  // },
  // {
  //   title: '状态',
  //   dataIndex: 'Status',
  //   key: 'Status',
  //   sorter: (a, b) => a.Status.localeCompare(b.Status),
  // },
  {
    title: '备注',
    dataIndex: 'Remark',
    key: 'Remark',
    sorter: (a, b) => a.Remake.localeCompare(b.Remake),
  },
];
