import {
  commonTextOption,
  commonMediumTextOption,
  commonLargeTextOption,
  commonValueOption,
  commonMediumFormatValueOption,
  commonDateOption,
  getFormatter,
} from '/@/views/dataAnalysis/components/BaseVxeTable/config';
import { dimensionCommonFormOptions } from '../../config';
import { BaseVxeTableTypes, EColumnType } from '/@/views/dataAnalysis/components/BaseVxeTable/types';
import { TFormItemOption } from '/@/views/dataAnalysis/components/BaseSearchForm/types';
// 表单配置
export const formOptions: TFormItemOption[] = [...dimensionCommonFormOptions];

export const getAllColumns = (): BaseVxeTableTypes.Columns => {
  const columns: BaseVxeTableTypes.Columns = [
    { type: 'seq', title: '序号', width: 50, fixed: 'left' },
    //     "factory" => "厂区",
    // "year" => "年",
    // "month" => "月",
    // "week" => "周",
    // "ywfw" => "仓库业务范围",
    // "werks" => "工厂",
    // "dayDateStr" => "实际货物移动日期",
    // "charg" => "批号",
    // "gsber" => "021本身业务范围",
    // "sjly" => "取数来源",
    // "matnr" => "物料编码",
    { ...commonTextOption, title: '厂区', field: 'factory' },
    { ...commonTextOption, title: '年', field: 'year' },
    { ...commonTextOption, title: '月', field: 'month' },
    { ...commonTextOption, title: '周', field: 'week' },
    { ...commonTextOption, title: '仓库业务范围', field: 'ywfw' },
    { ...commonTextOption, title: '工厂', field: 'werks' },
    { ...commonDateOption, title: '实际货物移动日期', field: 'dayDateStr' },
    { ...commonTextOption, title: '批号', field: 'charg' },
    { ...commonTextOption, title: '021本身业务范围', field: 'gsber' },
    { ...commonTextOption, title: '取数来源', field: 'sjly' },
    { ...commonTextOption, title: '物料编码', field: 'matnr' },

    // "netprs" => "销售未税单价",
    // "lgmngs" => "未开票数量",
    // "hl" => "汇率",
    // "vmiFc" => "VMI_发出收入",
    // "khgx" => "客户关系",
    // "khlb" => "客户类别",
    // "cplb" => "产品类别",
    // "bezei" => "销售凭证类型描述",
    // "bukrsVf" => "公司代码",
    // "name1A" => "公司代码或公司的名称",
    { ...commonMediumFormatValueOption, width: 80, title: '销售未税单价', field: 'netprs', formatter: getFormatter({ decimal: 6 }) },
    { ...commonMediumFormatValueOption, width: 80, title: '未开票数量', field: 'lgmngs' },
    { ...commonMediumFormatValueOption, width: 80, title: '汇率', field: 'hl' },
    { ...commonMediumFormatValueOption, width: 80, title: 'VMI_发出收入', field: 'vmiFc' },
    { ...commonTextOption, title: '客户关系', field: 'khgx' },
    { ...commonTextOption, title: '客户类别', field: 'khlb' },
    { ...commonTextOption, title: '产品类别', field: 'cplb' },
    { ...commonTextOption, title: '销售凭证类型描述', field: 'bezei' },
    { ...commonTextOption, title: '公司代码', field: 'bukrsVf' },
    { ...commonLargeTextOption, title: '公司代码或公司的名称', field: 'name1A' },
    // "kunag" => "售达方",
    // "nameOrg1" => "组织名称 1",
    // "arktx" => "销售订单项目的短文本",
    // "audatStr" => "凭证日期(接收/发送日期)",
    // "vgbel" => "参考单据的单据编号",
    // "bstkd" => "客户PO号",
    // "waerk" => "销售和分销凭证货币币种",
    // "vbeln" => "销售和分销凭证号",
    { ...commonTextOption, title: '售达方', field: 'kunag' },
    { ...commonTextOption, title: '组织名称1', field: 'nameOrg1' },
    { ...commonLargeTextOption, title: '销售订单项目的短文本', field: 'arktx' },
    { ...commonDateOption, title: '凭证日期(接收/发送日期)', field: 'audatStr' },
    { ...commonLargeTextOption, title: '参考单据的单据编号', field: 'vgbel' },
    { ...commonTextOption, title: '客户PO号', field: 'bstkd' },
    { ...commonLargeTextOption, title: '销售和分销凭证货币币种', field: 'waerk' },
    { ...commonLargeTextOption, title: '销售和分销凭证号', field: 'vbeln' },
    // "posnr" => "销售和分销凭证的项目号",
    { ...commonLargeTextOption, title: '销售和分销凭证的项目号', field: 'posnr' },
    // "lgort" => "库存地点",
    // "lgobe" => "仓储地点的描述",
    // "name1" => "名称",
    // "name2" => "名称2",
    // "meins" => "基本计量单位",
    // "vrkme" => "销售单位",
    // "lfimg" => "实际已交货量(按销售单位)",
    // "zbgXg" => "信管专用BG",
    { ...commonTextOption, title: '库存地点', field: 'lgort' },
    { ...commonTextOption, title: '仓储地点的描述', field: 'lgobe' },
    { ...commonTextOption, title: '名称', field: 'name1' },
    { ...commonTextOption, title: '名称2', field: 'name2' },
    { ...commonTextOption, title: '基本计量单位', field: 'meins' },
    { ...commonTextOption, title: '销售单位', field: 'vrkme' },
    { ...commonMediumFormatValueOption, title: '实际已交货量(按销售单位)', field: 'lfimg' },
    { ...commonTextOption, title: '信管专用BG', field: 'zbgXg' },
  ];
  return columns;
};
