const columnList = [
  {
    label: '文件名称',
    prop: 'fileName',
    fixed: 'none',
    align: 'left',
    lydcKey: 'input',
    sortable: false,
    width: null,
    id: 'fileName',
    fullName: '文件名称',
    __config__: {
      lydcKey: 'input',
      label: '文件名称',
      tipLabel: '',
      showLabel: true,
      tag: 'LydcInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'convert_file_task',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 103,
      renderKey: 1726466513003,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'fileName',
  },
  {
    label: '目标格式',
    prop: 'targetFileType',
    fixed: 'none',
    align: 'left',
    lydcKey: 'radio',
    sortable: false,
    width: null,
    id: 'targetFileType',
    fullName: '目标格式',
    __config__: {
      lydcKey: 'radio',
      label: '目标格式',
      tipLabel: '',
      showLabel: true,
      tag: 'LydcRadio',
      tagIcon: 'icon-ym icon-ym-generator-radio',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '1',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'convert_file_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      templateJson: [],
      formId: 102,
      renderKey: 1726466242736,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        fullName: '转DXF',
        id: '1',
      },
      {
        fullName: '转DWG',
        id: '2',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    direction: 'horizontal',
    optionType: 'default',
    buttonStyle: 'solid',
    size: 'default',
    disabled: false,
    __vModel__: 'targetFileType',
  },
  {
    label: '源文件url',
    prop: 'sourceUrl',
    fixed: 'none',
    align: 'left',
    lydcKey: 'input',
    sortable: false,
    width: null,
    id: 'sourceUrl',
    fullName: '源文件url',
    __config__: {
      lydcKey: 'input',
      label: '源文件url',
      tipLabel: '',
      showLabel: true,
      tag: 'LydcInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'convert_file_task',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 101,
      renderKey: 1726466423646,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'sourceUrl',
  },
  {
    label: '脱敏文件url',
    prop: 'desensitizedUrl',
    fixed: 'none',
    align: 'left',
    lydcKey: 'input',
    sortable: false,
    width: null,
    id: 'desensitizedUrl',
    fullName: '脱敏文件url',
    __config__: {
      lydcKey: 'input',
      label: '脱敏文件url',
      tipLabel: '',
      showLabel: true,
      tag: 'LydcInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'convert_file_task',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 112,
      renderKey: 1726736825806,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'desensitizedUrl',
  },
  {
    label: '转换后文件url',
    prop: 'convertedUrl',
    fixed: 'none',
    align: 'left',
    lydcKey: 'input',
    sortable: false,
    width: null,
    id: 'convertedUrl',
    fullName: '转换后文件url',
    __config__: {
      lydcKey: 'input',
      label: '转换后文件url',
      tipLabel: '',
      showLabel: true,
      tag: 'LydcInput',
      tagIcon: 'icon-ym icon-ym-generator-input',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'convert_file_task',
      noShow: false,
      regList: [],
      trigger: 'blur',
      formId: 104,
      renderKey: 1726466519970,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
      blur: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    placeholder: '请输入',
    useScan: false,
    useMask: false,
    maskConfig: {
      filler: '*',
      maskType: 1,
      prefixType: 1,
      prefixLimit: 0,
      prefixSpecifyChar: '',
      suffixType: 1,
      suffixLimit: 0,
      suffixSpecifyChar: '',
      ignoreChar: '',
      useUnrealMask: false,
      unrealMaskLength: 1,
    },
    clearable: true,
    addonBefore: '',
    addonAfter: '',
    prefixIcon: '',
    suffixIcon: '',
    maxlength: null,
    showCount: false,
    showPassword: false,
    readonly: false,
    disabled: false,
    __vModel__: 'convertedUrl',
  },
  {
    label: '转换状态',
    prop: 'convertStatus',
    fixed: 'none',
    align: 'left',
    lydcKey: 'select',
    sortable: false,
    width: null,
    id: 'convertStatus',
    fullName: '转换状态',
    __config__: {
      lydcKey: 'select',
      label: '转换状态',
      tipLabel: '',
      showLabel: true,
      tag: 'LydcSelect',
      tagIcon: 'icon-ym icon-ym-generator-select',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'convert_file_task',
      noShow: false,
      regList: [],
      trigger: 'change',
      dataType: 'static',
      dictionaryType: '',
      propsUrl: '',
      propsName: '',
      templateJson: [],
      formId: 111,
      renderKey: 1726466720217,
    },
    on: {
      change: '({ data, rowIndex, formData, setFormData, setShowOrHide, setRequired, setDisabled, onlineUtils }) => {\n    // 在此编写代码\n    \n}',
    },
    style: {
      width: '100%',
    },
    options: [
      {
        fullName: '等待',
        id: '0',
      },
      {
        fullName: '进行中',
        id: '1',
      },
      {
        fullName: '已脱敏',
        id: '2',
      },
      {
        fullName: '已转换',
        id: '3',
      },
    ],
    props: {
      label: 'fullName',
      value: 'id',
    },
    placeholder: '请选择',
    clearable: true,
    disabled: false,
    filterable: false,
    multiple: false,
    __vModel__: 'convertStatus',
  },
  {
    label: '创建用户',
    prop: 'creatorUserName',
    fixed: 'none',
    align: 'left',
    lydcKey: 'createUser',
    sortable: false,
    width: null,
    id: 'creatorUserName',
    fullName: '创建用户',
    __config__: {
      lydcKey: 'createUser',
      label: '创建用户',
      showLabel: true,
      tag: 'LydcOpenData',
      tagIcon: 'icon-ym icon-ym-generator-founder',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      required: false,
      layout: 'colFormItem',
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'convert_file_task',
      noShow: false,
      formId: 109,
      renderKey: 1726466648655,
    },
    style: {
      width: '100%',
    },
    type: 'currUser',
    readonly: true,
    placeholder: '',
    __vModel__: 'creatorUserName',
  },
  {
    label: '创建时间',
    prop: 'creatorTime',
    fixed: 'none',
    align: 'left',
    lydcKey: 'createTime',
    sortable: false,
    width: null,
    id: 'creatorTime',
    fullName: '创建时间',
    __config__: {
      lydcKey: 'createTime',
      label: '创建时间',
      showLabel: true,
      tag: 'LydcOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'convert_file_task',
      noShow: false,
      formId: 110,
      renderKey: 1726466650170,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'creatorTime',
  },

  {
    label: '完成时间',
    prop: 'finishTime',
    fixed: 'none',
    align: 'left',
    lydcKey: 'createTime',
    sortable: false,
    width: null,
    id: 'finishTime',
    fullName: '完成时间',
    __config__: {
      lydcKey: 'createTime',
      label: '完成时间',
      showLabel: true,
      tag: 'LydcOpenData',
      tagIcon: 'icon-ym icon-ym-generator-createtime',
      tableAlign: 'left',
      tableFixed: 'none',
      className: [],
      defaultValue: '',
      layout: 'colFormItem',
      required: false,
      span: 24,
      dragDisabled: false,
      visibility: ['pc', 'app'],
      tableName: 'convert_file_task',
      noShow: false,
      formId: 115,
      renderKey: 1726736868381,
    },
    style: {
      width: '100%',
    },
    type: 'currTime',
    readonly: true,
    placeholder: '',
    __vModel__: 'finishTime',
  },
];
export default columnList;
