import type { VxeGridPropTypes } from '/@/components/VxeTable';

import { useI18n } from '/@/hooks/web/useI18n';
import {
  repairOptions,
  // moldProcessingMethodOptions,
  renderMultiplePerson,
  renderCustomText,
  REASON_ENUM,
  EXCEPTION_CATEGORY_ENUM,
} from '/@/views/productionDeal/mouldBusiness/maintenance/config';
import { useBaseStore } from '/@/store/modules/base';
import { getSupplierlist } from '/@/api/engineering/mould';
import { getFactoryList } from '/@/api/business/shippingspace';

const { t } = useI18n();
const baseStore = useBaseStore();

/**
 * 单据状态枚举
 */
export enum STATUS_ENUM {
  暂存 = 0,
  在办 = 1,
  撤回 = 2,
  驳回 = 3,
  终止 = 4,
  结案 = 5,
}

/**
 * 单据状态选项及显示标签配置
 */
export const statusOptions = [
  {
    label: t('dict.ProgressStatusEnum.0'),
    value: STATUS_ENUM.暂存,
    fullName: t('dict.ProgressStatusEnum.0'),
    id: STATUS_ENUM.暂存,
    theme: 'gray',
    rowKey: 'confirmStatus',
  },
  {
    label: t('dict.ProgressStatusEnum.1'),
    value: STATUS_ENUM.在办,
    fullName: t('dict.ProgressStatusEnum.1'),
    id: STATUS_ENUM.在办,
    theme: 'blue',
    rowKey: 'confirmStatus',
  },
  {
    label: t('dict.ProgressStatusEnum.4'),
    value: STATUS_ENUM.撤回,
    fullName: t('dict.ProgressStatusEnum.4'),
    id: STATUS_ENUM.撤回,
    theme: 'purple',
    rowKey: 'confirmStatus',
  },
  {
    label: t('dict.ProgressStatusEnum.3'),
    value: STATUS_ENUM.驳回,
    fullName: t('dict.ProgressStatusEnum.3'),
    id: STATUS_ENUM.驳回,
    theme: 'yellow',
    rowKey: 'confirmStatus',
  },
  {
    label: t('dict.ProgressStatusEnum.2'),
    value: STATUS_ENUM.终止,
    fullName: t('dict.ProgressStatusEnum.2'),
    id: STATUS_ENUM.终止,
    theme: 'red',
    rowKey: 'confirmStatus',
  },
  {
    label: t('dict.ProgressStatusEnum.5'),
    value: STATUS_ENUM.结案,
    fullName: t('dict.ProgressStatusEnum.5'),
    id: STATUS_ENUM.结案,
    theme: 'green',
    rowKey: 'confirmStatus',
  },
];

/**
 * 清单页 - 搜索表单配置
 */
export function getFormConfig() {
  return [
    {
      fieldName: 'moldRepairApplyNo',
      label: '',
      component: 'Input',
      componentProps: {
        placeholder: '单号',
        allowClear: true,
      },
      width: 100,
    },
    {
      fieldName: 'moldNo',
      label: '',
      component: 'Input',
      componentProps: {
        placeholder: '模具料号',
        allowClear: true,
      },
    },
    {
      fieldName: 'moldType',
      label: '',
      component: 'ApiSelect',
      componentProps: {
        placeholder: '模具类型',
        api: () => baseStore.getDictionaryData('MoldApply.MoldType'),
        resultField: 'data',
        labelField: 'fullName',
        valueField: 'enCode',
        allowClear: true,
      },
    },
    // {
    //   fieldName: 'currentProcessorId',
    //   label: '',
    //   component: 'CustomUserSelect',
    //   i18nField: 'CommonCol.currentNodeUser',
    //   componentProps: {
    //     placeholder: '当前处理人',
    //     allowClear: true,
    //   },
    // },
    {
      fieldName: 'status',
      label: '',
      component: 'Select',
      componentProps: {
        placeholder: '状态',
        allowClear: true,
        options: statusOptions,
      },
    },
  ];
}

/**
 * 清单页 - 表格列配置
 */
export function getColumn(): Array<VxeGridPropTypes.Column & Partial<Record<'i18nField', string>>> {
  return [
    {
      type: 'checkbox',
      field: 'checkbox',
    },
    {
      field: 'seq',
      title: t('component.table.index'),
      type: 'seq',
      width: '50',
      align: 'center',
    },
    {
      title: '单号',
      field: 'moldRepairApplyNo',
      sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'Input' },
      width: 200,
      slots: {
        default: 'moldRepairApplyNo',
      },
    },
    {
      title: '需求类型',
      field: 'demandType',
      formatter: ({ cellValue, row }) => row.demandTypeName || cellValue || '',
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'Input' },
      width: 200,
    },
    // {
    //   title: '供应商意见',
    //   field: 'supplierOpinion',
    //   // sortable: true,
    //   // filters: [{ data: '' }],
    //   // filterRender: { name: 'Input' },
    //   width: 200,
    // },
    // {
    //   title: '变更',
    //   field: 'changeType',
    //   formatter: ({ cellValue, row }) => row.changeTypeName || cellValue || '',
    //   // sortable: true,
    //   filters: [{ data: '' }],
    //   filterRender: { name: 'ASelect', props: { options: repairOptions } },
    //   width: 200,
    // },
    {
      title: '产品内部料号',
      field: 'insidePartNumber',
      // sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
    },
    {
      title: 'SAP工单号',
      field: 'sapWorkOrderNo',
      // sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
    },
    {
      title: '模具料号',
      field: 'moldNo',
      // sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
    },
    {
      title: '模具类型',
      field: 'moldType',
      formatter: ({ cellValue, row }) => row.moldTypeName || cellValue || '',
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'Input' },
      width: 200,
    },
    {
      title: '模具状态',
      field: 'moldStatus',
      i18nField: 'moldStatus',
      formatter: ({ cellValue, row }) => row.moldStatusName || cellValue || '',
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: {
        name: 'ApiSelect',
        props: {
          api: () => baseStore.getDictionaryData('MoldLedgerStatusEnum'),
          resultField: 'data',
          labelField: 'fullName',
          valueField: 'enCode',
          immediate: true,
          showSearch: false,
          filterOption: false,
          notFoundContent: null,
          style: { width: '200px' },
        },
      },
      width: 200,
    },
    {
      title: '供应商',
      field: 'supplier',
      formatter: ({ cellValue, row }) => row.supplierName || cellValue || '',
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: {
        name: 'ApiSelect',
        props: {
          api: getSupplierlist,
          apiSearch: {
            show: true,
            searchName: 'searchKey',
          },
          showSearch: true,
          filterOption: false,
          resultField: 'data',
          labelField: 'name',
          valueField: 'code',
          immediate: true,
          alwaysLoad: true,
          style: { width: '200px' },
        },
      },
      width: 200,
    },
    {
      title: '需求返厂日期',
      field: 'demandReturnDate',
      sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'DateRange' },
      width: 200,
      cellRender: {
        name: 'Date',
        // @ts-ignore
        format: 'YYYY-MM-DD',
      },
    },
    {
      title: '费用归属',
      field: 'costAttribution',
      formatter: ({ cellValue, row }) => row.costAttributionName || cellValue || '',
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: {
        name: 'ApiSelect',
        props: {
          api: () => baseStore.getDictionaryData('CostAttribution'),
          resultField: 'data',
          labelField: 'fullName',
          valueField: 'enCode',
          immediate: true,
          showSearch: false,
          filterOption: false,
          notFoundContent: null,
          style: { width: '200px' },
        },
      },
      width: 200,
    },
    {
      title: '维修次数',
      field: 'repairCount',
      sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
      aqpFilter: { cSharpType: 'int' },
    },
    {
      title: '预估寿命(KPCS)',
      field: 'estimateLifespan',
      sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
      aqpFilter: { cSharpType: 'int' },
    },
    {
      title: '已使用寿命(KPCS)',
      field: 'usedLifespan',
      sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
      aqpFilter: { cSharpType: 'int' },
    },
    {
      title: '原因分析',
      field: 'causeAnalysis',
      formatter: ({ cellValue, row }) => renderCustomText(cellValue, row, 'causeAnalysisName', 'otherCauseAnalysis', REASON_ENUM.其他),
      // sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
    },
    {
      title: '维修内容(改善对策)',
      field: 'repairContent',
      // sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
    },
    {
      title: '维修类型',
      field: 'repairType',
      formatter: ({ cellValue, row }) => row.repairTypeName || cellValue || '',
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'ASelect', props: { options: repairOptions, style: { width: '200px' } } },
      width: 200,
    },
    {
      title: '维修类型变更日志',
      field: 'repairChangeLog',
      // sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
      slots: {
        default: 'repairChangeLog',
      },
    },
    // {
    //   title: '变更维修类型',
    //   field: 'changeRepairTypeName',
    //   // sortable: true,
    //   filters: [{ data: '' }],
    //   filterRender: { name: 'ASelect', props: { options: repairOptions } },
    //   width: 200,
    // },
    // {
    //   title: '变更原因',
    //   field: 'changeReason',
    //   // sortable: true,
    //   // filters: [{ data: '' }],
    //   // filterRender: { name: 'Input' },
    //   width: 200,
    // },
    // {
    //   title: '模具处理方式',
    //   field: 'dealType',
    //   formatter: ({ cellValue, row }) => row.dealTypeName || cellValue || '',
    //   // sortable: true,
    //   filters: [{ data: '' }],
    //   filterRender: { name: 'ASelect', props: { options: moldProcessingMethodOptions } },
    //   width: 200,
    // },
    // {
    //   title: '变更附件',
    //   field: 'attachFileNames',
    //   // sortable: true,
    //   // filters: [{ data: '' }],
    //   // filterRender: { name: 'AInput' },
    //   slots: {
    //     default: 'attachFileNames',
    //   },
    //   width: 200,
    // },
    {
      title: '图纸',
      field: 'drawingsName',
      // sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'AInput' },
      width: 200,
      slots: {
        default: 'drawingsName',
      },
    },
    // {
    //   title: '审核人',
    //   field: 'reviewerName',
    //   // sortable: true,
    //   filters: [{ data: '' }],
    //   filterRender: { name: 'Input' },
    //   width: 200,
    // },
    // {
    //   title: '审核意见',
    //   field: 'reviewOpinion',
    //   // sortable: true,
    //   // filters: [{ data: '' }],
    //   // filterRender: { name: 'Input' },
    //   width: 200,
    // },
    {
      title: '异常类别',
      field: 'exceptionCategory',
      formatter: ({ cellValue, row }) => renderCustomText(cellValue, row, 'exceptionCategoryName', 'otherExceptionCategory', EXCEPTION_CATEGORY_ENUM.其他),
      // sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
    },
    {
      title: '问题描述',
      field: 'issueDescription',
      // sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
    },
    {
      title: '工厂',
      field: 'factory',
      formatter: ({ cellValue, row }) => row.factoryName || cellValue || '',
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: {
        name: 'ApiSelect',
        props: {
          api: getFactoryList,
          showSearch: true,
          apiSearch: {
            show: true,
            searchName: 'factoryCode',
          },
          params: {
            pageSize: 20,
          },
          resultField: 'data',
          labelField: 'Name',
          valueField: 'Code',
          filterOption: false,
          notFoundContent: null,
          style: { width: '200px' },
        },
      },
      width: 200,
    },
    {
      title: '发生时间',
      field: 'occurrenceTime',
      sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
      cellRender: {
        name: 'Date',
        // @ts-ignore
        format: 'YYYY-MM-dd HH:mm:ss',
      },
    },
    {
      title: '检验文件',
      field: 'inspectionDocument',
      // sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
    },
    // {
    //   title: '生产数量(KPCS)',
    //   field: 'productionQuantity',
    //   // sortable: true,
    //   // filters: [{ data: '' }],
    //   // filterRender: { name: 'Input' },
    //   width: 200,
    // },
    {
      title: '不良数(KPCS)',
      field: 'defectiveCountKpcs',
      sortable: true,
      // filters: [{ data: '' }],
      // filterRender: { name: 'Input' },
      width: 200,
      aqpFilter: { cSharpType: 'int' },
    },
    {
      title: '生产人员',
      field: 'productionStaff',
      formatter: ({ cellValue, row }) => renderMultiplePerson(cellValue, row, 'productionStaffName'),
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'CustomUserSelect', props: { style: { width: '200px' } } },
      width: 200,
    },
    {
      title: '组长',
      field: 'teamLeader',
      formatter: ({ cellValue, row }) => renderMultiplePerson(cellValue, row, 'teamLeaderName'),
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'CustomUserSelect', props: { style: { width: '200px' } } },
      width: 200,
    },
    {
      title: '主管',
      field: 'supervisor',
      formatter: ({ cellValue, row }) => renderMultiplePerson(cellValue, row, 'supervisorName'),
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'CustomUserSelect', props: { style: { width: '200px' } } },
      width: 200,
    },
    {
      title: '工程/生技',
      field: 'engineeringTechnician',
      formatter: ({ cellValue, row }) => row.engineeringTechnicianName || cellValue || '',
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'CustomUserSelect', props: { style: { width: '200px' } } },
      width: 200,
    },
    {
      title: '模具采购员',
      field: 'moldPurchaser',
      formatter: ({ cellValue, row }) => row.moldPurchaserName || cellValue || '',
      sortable: true,
      // filters: [{ data: '' }],
      filterRender: { name: 'CustomUserSelect', props: { style: { width: '200px' } } },
      width: 200,
    },
    {
      title: '仓管员',
      field: 'warehouseManager',
      formatter: ({ cellValue, row }) => renderMultiplePerson(cellValue, row, 'warehouseManagerName'),
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'CustomUserSelect', props: { style: { width: '200px' } } },
      width: 200,
    },
    {
      title: '退料人',
      field: 'materialReturner',
      formatter: ({ cellValue, row }) => renderMultiplePerson(cellValue, row, 'materialReturnerName'),
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'CustomUserSelect', props: { style: { width: '200px' } } },
      width: 200,
    },
    {
      title: '制单人',
      field: 'documentPreparer',
      formatter: ({ cellValue, row }) => row.documentPreparerName || cellValue || '',
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'CustomUserSelect', props: { style: { width: '200px' } } },
      width: 200,
    },
    {
      title: '申请部门',
      field: 'requestingDepartment',
      // sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'Input' },
      width: 200,
    },
    // 创建时间
    {
      title: '创建时间',
      field: 'creatorTime',
      showOverflow: 'tooltip',
      sortable: true,
      filters: [{ data: '' }],
      filterRender: { name: 'DateRange' },
      width: '120',
      cellRender: {
        name: 'Date',
        // @ts-ignore
        format: 'YYYY-MM-dd HH:mm:ss',
      },
    },
    // 操作行
    {
      title: t('common.action'),
      width: '80',
      field: 'action',
      fixed: 'right',
      slots: {
        default: 'action',
      },
    },
  ];
}
