import {
  commonTextOption,
  commonMediumTextOption,
  commonValueOption,
  commonMediumFormatValueOption,
  commonDateOption,
  getFormatter,
} from '/@/views/dataAnalysis/components/BaseVxeTable/config';
import { dimensionCommonFormOptions } from '../../config';
import { BaseVxeTableTypes, EColumnType } from '/@/views/dataAnalysis/components/BaseVxeTable/types';
import { TFormItemOption } from '/@/views/dataAnalysis/components/BaseSearchForm/types';
// 表单配置
export const formOptions: TFormItemOption[] = [...dimensionCommonFormOptions];

export const getAllColumns = (): BaseVxeTableTypes.Columns => {
  const columns: BaseVxeTableTypes.Columns = [
    { type: 'seq', title: '序号', width: 50, fixed: 'left' },
    //     "factory" => "厂区",
    // "year" => "年",
    // "month" => "月",
    // "week" => "周",
    // "dayDateStr" => "收货日期",
    // "matnr" => "料号",
    // "werks" => "工厂代码",
    // "charg" => "批次",
    // "menge" => "收货数量",
    // "dj" => "单价",
    // "kcje" => "库存收入金额",
    { ...commonTextOption, title: '厂区', field: 'factory' },
    { ...commonTextOption, title: '年', field: 'year' },
    { ...commonTextOption, title: '月', field: 'month' },
    { ...commonTextOption, title: '周', field: 'week' },
    { ...commonTextOption, title: '收货日期', field: 'dayDateStr' },
    { ...commonTextOption, title: '料号', field: 'matnr' },
    { ...commonTextOption, title: '工厂代码', field: 'werks' },
    { ...commonTextOption, title: '批次', field: 'charg' },
    { ...commonMediumFormatValueOption, width: 80, title: '收货数量', field: 'menge' },
    { ...commonMediumFormatValueOption, width: 60, title: '单价', field: 'dj', formatter: getFormatter({ decimal: 6 }) },
    { ...commonMediumFormatValueOption, width: 80, title: '库存收入金额', field: 'kcje' },
    // "company" => "公司",
    // "companyCode" => "公司代码",
    // "typeName" => "产品类型缩写",
    // "typeNameCn" => "产品类型中文",
    // "types" => "产品类型",
    // "isGoodProduct" => "是否良品",
    // "lgort" => "库存地点",
    // "price" => "成本单价",
    { ...commonTextOption, title: '公司', field: 'company' },
    { ...commonTextOption, title: '公司代码', field: 'companyCode' },
    { ...commonTextOption, title: '产品类型缩写', field: 'typeName' },
    { ...commonTextOption, title: '产品类型中文', field: 'typeNameCn' },
    { ...commonTextOption, title: '产品类型', field: 'types' },
    { ...commonTextOption, title: '是否良品', field: 'isGoodProduct' },
    { ...commonTextOption, title: '库存地点', field: 'lgort' },
    { ...commonMediumFormatValueOption, title: '成本单价', field: 'price' },
    // "sprice" => "财务月结后成本单价",
    // "zdmbtr" => "库存成本金额",
    // "menge0" => "按照库龄取库龄小于30天的数量",
    // "dmbtr0" => "按照库龄取库龄小于30天的金额",
    { ...commonMediumFormatValueOption, title: '财务月结后成本单价', field: 'sprice' },
    { ...commonMediumFormatValueOption, title: '库存成本金额', field: 'zdmbtr' },
    { ...commonMediumFormatValueOption, width: 120, title: '按照库龄取库龄小于30天的数量', field: 'menge0' },
    { ...commonMediumFormatValueOption, width: 120, title: '按照库龄取库龄小于30天的金额', field: 'dmbtr0' },
    // "menge1" => "30-45 数量",
    // "dmbtr1" => "30-45 金额",
    // "menge2" => "45-60 数量",
    // "dmbtr2" => "45-60 金额",
    // "Menge3" => "60-90 数量",
    // "dmbtr3" => "60-90 金额",
    // "menge4" => "90-180 数量",
    // "dmbtr4" => "90-180 金额",
    // "menge5" => "180-360 数量",
    // "dmbtr5" => "180-360 金额",
    // "menge6" => "360以上 数量",
    // "dmbtr6" => "360以上 金额",
    { ...commonMediumFormatValueOption, title: '30-45 数量', field: 'menge1' },
    { ...commonMediumFormatValueOption, title: '30-45 金额', field: 'dmbtr1' },
    { ...commonMediumFormatValueOption, title: '45-60 数量', field: 'menge2' },
    { ...commonMediumFormatValueOption, title: '45-60 金额', field: 'dmbtr2' },
    { ...commonMediumFormatValueOption, title: '60-90 数量', field: 'Menge3' },
    { ...commonMediumFormatValueOption, title: '60-90 金额', field: 'dmbtr3' },
    { ...commonMediumFormatValueOption, title: '90-180 数量', field: 'menge4' },
    { ...commonMediumFormatValueOption, title: '90-180 金额', field: 'dmbtr4' },
    { ...commonMediumFormatValueOption, title: '180-360 数量', field: 'menge5' },
    { ...commonMediumFormatValueOption, title: '180-360 金额', field: 'dmbtr5' },
    { ...commonMediumFormatValueOption, title: '360以上 数量', field: 'menge6' },
    { ...commonMediumFormatValueOption, title: '360以上 金额', field: 'dmbtr6' },
    // "name1" => "仓储地点描述列",
    // "source" => "来源",
    // "address" => "地址",
    // "isBonded" => "是否保税",
    // "etlDateStr" => "数据处理日期",
    // "cplb2" => "产品类别_2",
    // "lb2" => "类别2",
    // "zdays" => "库龄",
    { ...commonMediumFormatValueOption, title: '仓储地点描述列', field: 'name1' },
    { ...commonTextOption, title: '来源', field: 'source' },
    { ...commonTextOption, title: '地址', field: 'address' },
    { ...commonTextOption, title: '是否保税', field: 'isBonded' },
    { ...commonMediumFormatValueOption, title: '数据处理日期', field: 'etlDateStr' },
    { ...commonTextOption, title: '产品类别_2', field: 'cplb2' },
    { ...commonTextOption, title: '类别2', field: 'lb2' },
    { ...commonMediumFormatValueOption, title: '库龄', field: 'zdays' },

    // "ownProjectName" => "内部项目",
    // "custProjectName" => "外部项目",
    // "sobkz" => "特殊库存标识",
    // "wuwzz" => "委外在制",
    // "yjtValue" => "已计提",
    // "wjtValue" => "未计提",
    // "meins" => "计量单位",
    // "mmMenge" => "平米数",
    // "khlb" => "客户类别",
    // "cplb" => "产品类别",
    { ...commonTextOption, title: '内部项目', field: 'ownProjectName' },
    { ...commonTextOption, title: '外部项目', field: 'custProjectName' },
    { ...commonTextOption, title: '特殊库存标识', field: 'sobkz' },
    { ...commonTextOption, title: '委外在制', field: 'wuwzz' },
    { ...commonTextOption, title: '已计提', field: 'yjtValue' },
    { ...commonTextOption, title: '未计提', field: 'wjtValue' },
    { ...commonTextOption, title: '计量单位', field: 'meins' },
    { ...commonMediumFormatValueOption, title: '平米数', field: 'mmMenge' },
    { ...commonTextOption, title: '客户类别', field: 'khlb' },
    { ...commonTextOption, title: '产品类别', field: 'cplb' },
  ];
  return columns;
};
